# Generated by Django 5.2.1 on 2026-07-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.RemoveField(
            model_name='movimientoinsumo',
            name='insumo',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='MovimientoInsumo',
        ),
    ]
