# Generated by Django 4.2.13 on 2026-06-19 02:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(blank=True, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('curso', models.CharField(choices=[('3A', '3° A'), ('3B', '3° B'), ('4A', '4° A'), ('4B', '4° B'), ('5A', '5° A'), ('5B', '5° B')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/alumnos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#2E86DE', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='PROA Villa del Totoral', max_length=100)),
                ('dias_maximo_prestamo', models.PositiveIntegerField(default=2)),
                ('dias_aviso_mantenimiento', models.PositiveIntegerField(default=7)),
                ('email_alertas', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADA', 'Prestada'), ('REPARACION', 'En Reparación'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/herramientas/')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('metros', 'Metros'), ('litros', 'Litros'), ('gramos', 'Gramos'), ('hojas', 'Hojas'), ('rollos', 'Rollos')], default='unidad', max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PREV', 'Preventivo'), ('CORR', 'Correctivo')], max_length=4)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='core.herramienta')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['proxima_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('duracion_estimada_min', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.planmantenimiento')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.docente')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumo')),
            ],
            options={
                'verbose_name': 'Entrega de Insumo',
                'verbose_name_plural': 'Entregas de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado_devolucion', models.CharField(blank=True, choices=[('BUEN_ESTADO', 'Buen estado'), ('DESGASTE', 'Desgaste leve'), ('REPARACION', 'Requiere reparación'), ('DANIO_GRAVE', 'Dañada gravemente')], max_length=15, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('notificado_vencimiento', models.BooleanField(default=False)),
                ('modulo_clase', models.CharField(blank=True, max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alumno')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.docente')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.herramienta')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de stock'), ('ENTREGA', 'Entrega a alumno'), ('AJUSTE', 'Ajuste manual')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.insumo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta en inventario'), ('ESTADO', 'Cambio de estado'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_eventos', to='core.herramienta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Herramienta',
                'verbose_name_plural': 'Historial de Herramientas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('realizado_por', models.CharField(blank=True, max_length=100)),
                ('es_externo', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='core.planmantenimiento')),
                ('tareas_completadas', models.ManyToManyField(blank=True, related_name='ejecuciones', to='core.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Ejecución de Mantenimiento',
                'verbose_name_plural': 'Ejecuciones de Mantenimiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
