# Generated by Django 5.2.1 on 2026-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('3A', '3° A'), ('3B', '3° B'), ('4A', '4° A'), ('4B', '4° B'), ('5A', '5° A'), ('5B', '5° B'), ('6A', '6° A'), ('6B', '6° B'), ('7A', '7° A'), ('7B', '7° B')], max_length=2),
        ),
    ]
