# Generated by Django 6.0.7 on 2026-07-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BAJO', 'Bajo'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=10),
        ),
    ]
