# Generated by Django 5.2.1 on 2026-07-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insumo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='estado',
        ),
    ]
