# Generated by Django 5.2.1 on 2026-08-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alumno_curso'),
        ('core', '0003_remove_insumo_estado'),
    ]

    operations = [
    ]
