# Generated by Django 6.0.5 on 2026-08-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alumno_curso'),
        ('core', '0003_remove_insumo_estado'),
    ]

    operations = [
    ]
